### ISSUE TITLE
Include basic instructions in the README file.

### ISSUE THREAD

**Issue by bvadorno** [Adorno-Lab/phd-thesis-lyx-template#1]
Hi @anachristinaac,

Please include basic instructions on how to use the template in the README file.

Thanks,
Bruno

**Comment by anachristinaac** [comment]
Hi @bvadorno,

I edited the README file. Could you please check if it's good as is?

Thanks,
Ana

**Comment by bvadorno** [comment]
Hi @anachristinaac,

Excellent. Thanks!

Bruno
